[CHK-1386] feat: add integration test stage for deploy pipeline
pagopa/pagopa-ecommerce-payment-methods-service pull request #48
Opened 2023-04-12 09:32 UTC by MarcoAGreco

This PR update the devops deploy pipeline adding two new steps of API tests to test the integration of the deployed microservice in the eCommerce environment. The stages test the development deployment, the blue UAT deployment and the green UAT deployment. 

#### List of Changes

- Add API integration tests in deploy pipeline

#### Motivation and Context

- Increase code quality
#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-04-13 07:19 UTC, giovanniberti requested changes

2023-04-13 07:19 UTC, giovanniberti commented on .devops/azure-templates/api-tests.yml
> +    continueOnError: true
See https://github.com/pagopa/pagopa-ecommerce-transactions-service/pull/189#discussion_r1165098714

2023-04-17 16:48 UTC, pietro-tota approved these changes
Just a comment

2023-04-17 16:48 UTC, pietro-tota commented on .devops/azure-templates/api-tests.yml
> +      newman run api-tests/checkout-tests/checkout-for-ecommerce-api.tests.json -e ${{ parameters.ENV_FILE }} --ignore-redirects --reporters cli,junit --reporter-junit-export Results/api-TEST.xml
differentiate output results file name based on env file (maybe interpolating env file name)

2023-04-19 07:49 UTC, infantesimone commented
to merge @MarcoAGreco

2023-04-20 08:50 UTC, merged