[CHK-1839] feat(sessions): add endpoint to associate NPG session to trnsaction id
pagopa/pagopa-ecommerce-payment-methods-service pull request #97
Opened 2023-08-31 13:20 UTC by giovanniberti

#### List of Changes

 * add endpoint to associate NPG session to trnsaction id

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-09-01 11:52 UTC, pietro-tota commented on api-spec/api.yaml
> +        '404':
Add here 409 response status code returned in case transactionId is already associated to the input sessionId

2023-09-01 11:54 UTC, pietro-tota requested changes

2023-09-01 11:54 UTC, pietro-tota commented on api-spec/api.yaml
> +        '500':
Add 409 CONFLICT response

2023-09-01 12:05 UTC, giovanniberti commented on api-spec/api.yaml
> +        '500':
Nice catch :)
Fixed in 9f1fea1

2023-09-01 12:15 UTC, pietro-tota approved these changes
🚀

2023-09-01 14:07 UTC, pietro-tota submitted a review, later dismissed
🚀

2023-09-04 07:27 UTC, Fernando-Granato approved these changes
🚀

2023-09-04 07:32 UTC, Fernando-Granato commented on src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
> +                .map(ignored -> ResponseEntity.ok(null));
Shouldn't it return a 204 http status?
```suggestion
                .map(ignored -> ResponseEntity::noContent);
```

2023-09-04 07:33 UTC, Fernando-Granato reviewed
I just left a comment 👀

2023-09-04 07:48 UTC, giovanniberti commented on src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
> +                .map(ignored -> ResponseEntity.ok(null));
Fixed in 4a814dd

2023-09-04 08:00 UTC, pietro-tota submitted a review, later dismissed

2023-09-04 08:02 UTC, Fernando-Granato submitted a review, later dismissed

2023-09-07 07:23 UTC, pietro-tota commented
Please fix broken junit tests

2023-09-07 07:23 UTC, giovanniberti commented
Fixed

2023-09-07 07:37 UTC, pietro-tota approved these changes

2023-09-07 12:19 UTC, merged